import { NextApiRequest, NextApiResponse } from 'next';

import { extractImageReferences } from '@/utils/app/imageHandler';

import { getOrSetSessionId, getUserId } from '../session/_utils';
import { getRedis, jsonGet, sessionKey } from '../session/redis';

import sharp from 'sharp';

export const config = {
  api: {
    responseLimit: '15mb',
  },
};

const THUMBNAIL_MAX_SIZE = 400;
const THUMBNAIL_QUALITY = 80;
const LEGACY_PUBLIC_ACCESS =
  process.env.GENERATED_IMAGE_LEGACY_PUBLIC !== 'false';

interface GeneratedImageRecord {
  data?: string;
  mimeType?: string;
  userId?: string;
  user?: string;
  sessionId?: string;
}

function imageHistoryKey(userId: string, sessionId: string): string {
  if (userId && userId !== 'anon') {
    return sessionKey(['user', userId, 'imagePanelHistory']);
  }
  return sessionKey(['session', sessionId, 'imagePanelHistory']);
}

function historyReferencesImage(history: unknown, imageId: string): boolean {
  if (!Array.isArray(history)) return false;
  return history.some((entry) => {
    if (!entry || typeof entry !== 'object') return false;
    const outputImageIds = (entry as { outputImageIds?: unknown })
      .outputImageIds;
    return Array.isArray(outputImageIds) && outputImageIds.includes(imageId);
  });
}

function recordMatchesRequestOwner(
  record: GeneratedImageRecord,
  userId: string,
  sessionId: string,
): boolean {
  const ownerUserId = record.userId || record.user;
  if (ownerUserId && ownerUserId === userId) return true;
  return Boolean(record.sessionId && record.sessionId === sessionId);
}

async function userConversationReferencesImage(
  userId: string,
  imageId: string,
): Promise<boolean> {
  if (!userId || userId === 'anon') return false;

  const redis = getRedis();
  const userConversationsKey = sessionKey(['user', userId, 'conversations']);
  const conversationIds = await redis.smembers(userConversationsKey);

  for (const conversationId of conversationIds) {
    const conversation = await jsonGet(
      sessionKey(['conversation', conversationId]),
    );
    const messages = conversation?.messages;
    if (!Array.isArray(messages)) continue;
    if (extractImageReferences(messages).includes(imageId)) {
      return true;
    }
  }

  const history = await jsonGet(
    sessionKey(['user', userId, 'conversationHistory']),
  );
  if (Array.isArray(history)) {
    for (const conversation of history) {
      const messages = conversation?.messages;
      if (
        Array.isArray(messages) &&
        extractImageReferences(messages).includes(imageId)
      ) {
        return true;
      }
    }
  }

  return false;
}

async function canAccessGeneratedImage(
  record: GeneratedImageRecord,
  imageId: string,
  userId: string,
  sessionId: string,
): Promise<boolean> {
  if (recordMatchesRequestOwner(record, userId, sessionId)) return true;

  const history = await jsonGet(imageHistoryKey(userId, sessionId));
  if (historyReferencesImage(history, imageId)) return true;

  return userConversationReferencesImage(userId, imageId);
}

/**
 * Serves images that were generated by the backend image_generation tool.
 *
 * The backend stores generated images in Redis under the key
 * `generated:image:{id}` as a JSON document with fields:
 *   - data: base64-encoded image bytes
 *   - mimeType: e.g. "image/png"
 *   - prompt: the generation prompt
 *   - createdAt: ISO timestamp
 *   - source: "image_generation"
 *
 * Query parameters:
 *   - thumbnail=true  Return a 400px-max JPEG thumbnail instead of the full image.
 */
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', ['GET']);
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { id, thumbnail } = req.query;

  if (!id || typeof id !== 'string') {
    return res.status(400).json({ error: 'Invalid image ID' });
  }

  // Basic input validation - UUIDs are hex + hyphens
  if (!/^[a-f0-9-]+$/i.test(id)) {
    return res.status(400).json({ error: 'Invalid image ID format' });
  }

  try {
    const redis = getRedis();
    const redisKey = `generated:image:${id}`;
    const sessionId = getOrSetSessionId(req, res);
    const userId = await getUserId(req, res);

    // Try RedisJSON first, fall back to plain GET
    let record: GeneratedImageRecord | null = null;
    try {
      const jsonResult = (await redis.call('JSON.GET', redisKey, '$')) as
        | string
        | null;
      if (jsonResult) {
        const parsed = JSON.parse(jsonResult);
        record = Array.isArray(parsed) ? parsed[0] : parsed;
      }
    } catch {
      // RedisJSON not available or key not JSON - try plain string
      const plainResult = await redis.get(redisKey);
      if (plainResult) {
        try {
          record = JSON.parse(plainResult);
        } catch {
          // Not JSON at all
        }
      }
    }

    if (!record || !record.data) {
      return res.status(404).json({ error: 'Image not found' });
    }

    const authorized = await canAccessGeneratedImage(
      record,
      id,
      userId,
      sessionId,
    );
    if (!authorized && !LEGACY_PUBLIC_ACCESS) {
      return res.status(403).json({ error: 'Forbidden' });
    }
    if (!authorized) {
      res.setHeader('X-Generated-Image-Legacy-Access', 'true');
    }

    const mimeType: string = record.mimeType || 'image/png';
    const wantThumbnail = thumbnail === 'true' || thumbnail === '1';

    // Decode base64 data
    const imageBuffer = Buffer.from(record.data, 'base64');

    if (wantThumbnail) {
      try {
        const thumbBuffer = await sharp(imageBuffer)
          .resize(THUMBNAIL_MAX_SIZE, THUMBNAIL_MAX_SIZE, {
            fit: 'inside',
            withoutEnlargement: true,
          })
          .jpeg({ quality: THUMBNAIL_QUALITY })
          .toBuffer();

        res.setHeader('Content-Type', 'image/jpeg');
        res.setHeader('Cache-Control', 'private, max-age=86400, immutable');
        res.setHeader('ETag', `"${id}-thumb"`);
        res.setHeader('X-Content-Type-Options', 'nosniff');
        return res.status(200).send(thumbBuffer);
      } catch {
        // Thumbnail generation failed - fall through to full image
      }
    }

    // Return full image
    res.setHeader('Content-Type', mimeType);
    res.setHeader('Cache-Control', 'private, max-age=86400, immutable');
    res.setHeader('ETag', `"${id}"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Length', imageBuffer.length.toString());

    return res.status(200).send(imageBuffer);
  } catch (error) {
    console.error('Error serving generated image:', error);
    return res.status(500).json({ error: 'Failed to retrieve image' });
  }
}
