import { NextApiRequest, NextApiResponse } from 'next';
import { getRedis } from '../session/redis';
import sharp from 'sharp';

export const config = {
  api: {
    responseLimit: '15mb',
  },
};

const THUMBNAIL_MAX_SIZE = 400;
const THUMBNAIL_QUALITY = 80;

/**
 * Serves images that were generated by the backend image_generation tool.
 *
 * The backend stores generated images in Redis under the key
 * `generated:image:{id}` as a JSON document with fields:
 *   - data: base64-encoded image bytes
 *   - mimeType: e.g. "image/png"
 *   - prompt: the generation prompt
 *   - createdAt: ISO timestamp
 *   - source: "image_generation"
 *
 * Query parameters:
 *   - thumbnail=true  Return a 400px-max JPEG thumbnail instead of the full image.
 */
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', ['GET']);
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { id, thumbnail } = req.query;

  if (!id || typeof id !== 'string') {
    return res.status(400).json({ error: 'Invalid image ID' });
  }

  // Basic input validation - UUIDs are hex + hyphens
  if (!/^[a-f0-9-]+$/i.test(id)) {
    return res.status(400).json({ error: 'Invalid image ID format' });
  }

  try {
    const redis = getRedis();
    const redisKey = `generated:image:${id}`;

    // Try RedisJSON first, fall back to plain GET
    let record: any = null;
    try {
      const jsonResult = await redis.call('JSON.GET', redisKey, '$') as string | null;
      if (jsonResult) {
        const parsed = JSON.parse(jsonResult);
        record = Array.isArray(parsed) ? parsed[0] : parsed;
      }
    } catch {
      // RedisJSON not available or key not JSON - try plain string
      const plainResult = await redis.get(redisKey);
      if (plainResult) {
        try {
          record = JSON.parse(plainResult);
        } catch {
          // Not JSON at all
        }
      }
    }

    if (!record || !record.data) {
      return res.status(404).json({ error: 'Image not found' });
    }

    const mimeType: string = record.mimeType || 'image/png';
    const wantThumbnail = thumbnail === 'true' || thumbnail === '1';

    // Decode base64 data
    const imageBuffer = Buffer.from(record.data, 'base64');

    if (wantThumbnail) {
      try {
        const thumbBuffer = await sharp(imageBuffer)
          .resize(THUMBNAIL_MAX_SIZE, THUMBNAIL_MAX_SIZE, {
            fit: 'inside',
            withoutEnlargement: true,
          })
          .jpeg({ quality: THUMBNAIL_QUALITY })
          .toBuffer();

        res.setHeader('Content-Type', 'image/jpeg');
        res.setHeader('Cache-Control', 'public, max-age=86400, immutable');
        res.setHeader('ETag', `"${id}-thumb"`);
        res.setHeader('X-Content-Type-Options', 'nosniff');
        return res.status(200).send(thumbBuffer);
      } catch {
        // Thumbnail generation failed - fall through to full image
      }
    }

    // Return full image
    res.setHeader('Content-Type', mimeType);
    res.setHeader('Cache-Control', 'public, max-age=86400, immutable');
    res.setHeader('ETag', `"${id}"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Length', imageBuffer.length.toString());

    return res.status(200).send(imageBuffer);
  } catch (error) {
    console.error('Error serving generated image:', error);
    return res.status(500).json({ error: 'Failed to retrieve image' });
  }
}
