const sanitizeContent = (content: string) => {
  return content
    .replace(/[#*_`\[\]()]/g, '')
    .replace(/\n+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
};

export const generateConversationTitle = (content: string, maxWords: number = 6): string => {
  if (!content || typeof content !== 'string') {
    return 'New Conversation';
  }

  const cleaned = sanitizeContent(content);
  if (!cleaned) {
    return 'New Conversation';
  }

  const words = cleaned.split(/\s+/).filter((word) => word.length > 0);
  if (words.length === 0) {
    return 'New Conversation';
  }

  const selectedWords = words.slice(0, maxWords);
  const title = selectedWords.join(' ');
  return words.length > maxWords ? `${title}...` : title;
};

export const isAutoGeneratedTitle = (title?: string, sourceContent?: string): boolean => {
  if (!title || !sourceContent) {
    return false;
  }

  return generateConversationTitle(sourceContent) === title.trim();
};
