// Generated by scripts/generate_protocol_types.py; edit protocol/model-profile.schema.json.
export const MODEL_PROFILES = ['default', 'deep', 'deep_max'] as const;

export type ModelProfile = (typeof MODEL_PROFILES)[number];
