// Generated by scripts/generate_protocol_types.py; edit protocol/source-policy.schema.json.
export const SOURCE_POLICY_IDS = [
  'curated_domains',
  'curated_feeds',
  'perplexity_search',
  'known_url_scrape',
  'nvidia_docs',
  'uploaded_documents',
  'workspace_data',
  'x_mcp',
  'cluster_state',
  'network_state',
  'repository_data',
  'fantasy_data',
] as const;

export type SourcePolicyId = (typeof SOURCE_POLICY_IDS)[number];

export interface SourcePolicy {
  enabledSources?: SourcePolicyId[];
  disabledSources?: SourcePolicyId[];
  requirePlanApproval?: boolean;
  maxResearchToolCalls?: number;
  notes?: string;
}
