import { generateConversationTitle, isAutoGeneratedTitle } from '@/utils/app/conversationName';

import { describe, expect, it } from 'vitest';

describe('generateConversationTitle', () => {
  it('should return "New Conversation" for empty string', () => {
    expect(generateConversationTitle('')).toBe('New Conversation');
  });

  it('should return "New Conversation" for null input', () => {
    expect(generateConversationTitle(null as any)).toBe('New Conversation');
  });

  it('should return "New Conversation" for undefined input', () => {
    expect(generateConversationTitle(undefined as any)).toBe('New Conversation');
  });

  it('should strip markdown characters', () => {
    expect(generateConversationTitle('**bold** text')).toBe('bold text');
  });

  it('should truncate to 6 words by default and add ellipsis', () => {
    const input = 'one two three four five six seven eight';
    const result = generateConversationTitle(input);
    expect(result).toBe('one two three four five six...');
  });

  it('should not add ellipsis when content fits within maxWords', () => {
    const input = 'short title';
    expect(generateConversationTitle(input)).toBe('short title');
  });

  it('should support custom maxWords', () => {
    const input = 'one two three four five';
    expect(generateConversationTitle(input, 3)).toBe('one two three...');
  });

  it('should collapse whitespace', () => {
    const input = 'too   many    spaces';
    expect(generateConversationTitle(input)).toBe('too many spaces');
  });

  it('should return "New Conversation" for whitespace-only input', () => {
    expect(generateConversationTitle('   \n\n  ')).toBe('New Conversation');
  });
});

describe('isAutoGeneratedTitle', () => {
  it('should return true when title matches generated title', () => {
    const content = 'Hello world how are you';
    const title = generateConversationTitle(content);
    expect(isAutoGeneratedTitle(title, content)).toBe(true);
  });

  it('should return false when title does not match', () => {
    expect(isAutoGeneratedTitle('Custom Title', 'Hello world')).toBe(false);
  });

  it('should return false for null title', () => {
    expect(isAutoGeneratedTitle(null as any, 'some content')).toBe(false);
  });

  it('should return false for undefined sourceContent', () => {
    expect(isAutoGeneratedTitle('Some Title', undefined as any)).toBe(false);
  });

  it('should return false when both are null', () => {
    expect(isAutoGeneratedTitle(null as any, null as any)).toBe(false);
  });
});
