{{- if and .Values.backend.enabled .Values.backend.persistence.enabled .Values.backend.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "daedalus.fullname" . }}-backend
  labels:
    {{- include "daedalus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  {{- if .Values.backend.persistence.storageClassName }}
  storageClassName: {{ .Values.backend.persistence.storageClassName }}
  {{- end }}
{{- end }}
