{{- if and .Values.jupyterlab.enabled .Values.jupyterlab.persistence.enabled .Values.jupyterlab.persistence.create (not .Values.jupyterlab.persistence.existingClaimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "daedalus.fullname" . }}-jupyterlab
  labels:
    {{- include "daedalus.labels" . | nindent 4 }}
    app.kubernetes.io/component: jupyterlab
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.jupyterlab.persistence.storageClassName }}
  storageClassName: {{ .Values.jupyterlab.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.jupyterlab.persistence.size }}
{{- end }}
