{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daedalus.fullname" . }}-redis
  labels:
    {{- include "daedalus.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "daedalus.name" . }}
      app.kubernetes.io/component: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "daedalus.name" . }}
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}"
          imagePullPolicy: {{ .Values.images.redis.pullPolicy }}
          args: ["redis-server", "--save", "60", "1", "--appendonly", "yes", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/rejson.so"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            {{- if .Values.redis.persistence.enabled }}
            - name: redis-data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if .Values.redis.persistence.enabled }}
        - name: redis-data
          {{- if and .Values.redis.persistence.create (not .Values.redis.persistence.existingClaimName) }}
          persistentVolumeClaim:
            claimName: {{ include "daedalus.fullname" . }}-redis
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Values.redis.persistence.existingClaimName }}
          {{- end }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daedalus.fullname" . }}-redis
  labels:
    {{- include "daedalus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "daedalus.name" . }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      name: redis
{{- end }}
