{{- if and .Values.frontend.enabled (not .Values.frontend.env.fromSecret) .Values.frontend.env.createSecret }}
{{- $secretName := printf "%s-frontend-env" (include "daedalus.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "daedalus.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.frontend.env.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
