{{- if and .Values.backend.default.enabled .Values.backend.default.env.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daedalus.fullname" . }}-backend-env
  labels:
    {{- include "daedalus.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.backend.default.env.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
