#!/usr/bin/env python3
"""Generate the cross-language source-policy contract without runtime tooling."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "protocol/source-policy.schema.json"


def render() -> dict[Path, str]:
    schema = json.loads(SCHEMA.read_text())
    try:
        ids = schema["$defs"]["SourcePolicyId"]["enum"]
    except (KeyError, TypeError) as exc:
        raise ValueError("SourcePolicyId must define an enum") from exc
    if (
        not isinstance(ids, list)
        or not ids
        or not all(isinstance(value, str) for value in ids)
    ):
        raise ValueError("SourcePolicyId enum must be a non-empty list of strings")
    if len(set(ids)) != len(ids):
        raise ValueError("SourcePolicyId enum must contain unique IDs")
    ts = [
        "// Generated by scripts/generate_protocol_types.py; edit protocol/source-policy.schema.json.",
        "export const SOURCE_POLICY_IDS = [",
    ]
    ts += [f"  '{value}'," for value in ids]
    ts += [
        "] as const;",
        "",
        "export type SourcePolicyId = (typeof SOURCE_POLICY_IDS)[number];",
        "",
        "export interface SourcePolicy {",
    ]
    py = [
        '"""Generated source-policy contract. Edit protocol/source-policy.schema.json."""',
        "",
        "from typing import Literal, TypedDict",
        "",
        "SourcePolicyId = Literal[",
    ]
    py += [f'    "{value}",' for value in ids]
    py += ["]", "", "SOURCE_POLICY_IDS: tuple[SourcePolicyId, ...] = ("]
    py += [f'    "{value}",' for value in ids]
    py += [")", "", "", "class SourcePolicy(TypedDict, total=False):"]
    types = {
        "boolean": ("boolean", "bool"),
        "integer": ("number", "int"),
        "string": ("string", "str"),
    }
    for name, definition in schema["properties"].items():
        if definition["type"] == "array":
            if definition.get("items") != {"$ref": "#/$defs/SourcePolicyId"}:
                raise ValueError(f"Unsupported array item schema for {name}")
            ts_type, py_type = "SourcePolicyId[]", "list[SourcePolicyId]"
        else:
            ts_type, py_type = types[definition["type"]]
        ts.append(f"  {name}?: {ts_type};")
        py.append(f"    {name}: {py_type}")
    ts.append("}")
    return {
        ROOT / "frontend/types/sourcePolicy.ts": "\n".join(ts) + "\n",
        ROOT / "builder/nat_helpers/src/nat_helpers/source_policy_types.py": "\n".join(
            py
        )
        + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        print("Stale protocol types: " + ", ".join(stale))
        print("Run python3 scripts/generate_protocol_types.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
