functions:
  current_datetime:
    _type: current_datetime
  list_collections:
    _type: nat_nv_ingest
    redis_url: "redis://daedalus-redis.daedalus.svc.cluster.local:6379"
    nv_ingest_host: "192.168.1.239"
    nv_ingest_port: 7670
    milvus_uri: "http://192.168.1.234:32073"
    minio_endpoint: "192.168.1.239:9000"
    minio_access_key: "minioadmin"
    minio_secret_key: "minioadmin"
    chunk_size: 1024
    chunk_overlap: 150
    embedder_dim: 2048
    recreate_collection: false
  nat_nv_ingest:
    _type: nat_nv_ingest
    redis_url: "redis://daedalus-redis.daedalus.svc.cluster.local:6379"
    nv_ingest_host: "192.168.1.239"
    nv_ingest_port: 7670
    milvus_uri: "http://192.168.1.234:32073"
    minio_endpoint: "192.168.1.239:9000"
    minio_access_key: "minioadmin"
    minio_secret_key: "minioadmin"
    chunk_size: 1024
    chunk_overlap: 150
    embedder_dim: 2048
    recreate_collection: false

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0

workflow:
  _type: react_agent
  llm_name: nim_llm
  tool_names: [current_datetime, list_collections, nat_nv_ingest]
